<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">Meta Daten  </h3>
    </div>

    <div class="panel-body">


        <table class="table responsive table-striped table-hover">
            <tbody>
                <tr>
                    <th>ID</th>
                    <td><?= $this->infoscript->getInseratId(); ?></td>
                </tr>
                <tr>
                    <th>START</th>
                    <td><?= $this->infoscript->getStart();     ?></td>
                </tr>
                <tr>
                    <th>ENDE</th>
                    <td><?= $this->infoscript->getEnde();      ?></td>
                </tr>
                <tr>
                    <th>URL</th>
                    <td><?= $this->infoscript->getUrl();       ?></td>
                </tr>

            </tbody>


        </table>
    </div>
</div>