<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Bildschirme  </h3>
    </div>
    <div class="panel-body">
        
        <table class="table table-responsive table-striped table-hover">
            <thead>
                <tr>
                    <th>ID                     </th>
                    <th>BESCHREIBUNG           </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->infoscript->getBildschirme() as $bildschirm) : ?>
                <tr>
                    <td><?= $bildschirm->getId(); ?></td>
                    <td><?= $bildschirm->getBeschreibung() ?> </td>
                    <td><a class="btn-sm btn-danger pull-right" href=" <?=$this->actionUrls['delete'] . '/id=' . $this->infoscript->getInseratId() . "/display=" . $bildschirm->getId(); ?> "> löschen </a></td>
                </tr>
                <?php endforeach; ?>

                <?php foreach ($this->bildschirme as $bildschirm) : ?>
                <tr>
                    <td><?= $bildschirm->getId(); ?></td>
                    <td><?= $bildschirm->getBeschreibung(); ?> </td>
                    <td><a class="btn-sm btn-success pull-right" href=" <?=$this->actionUrls['add'] . '/id=' . $this->infoscript->getInseratId() . "/display=" . $bildschirm->getId(); ?> "> hinzufügen </a></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
    </div>
</div>