<?php $aktivieren   = "<a class=\"btn btn-success\"  href=\"#\" > aktivieren </a> ";   ?>
<?php $deaktivieren = "<a class=\"btn btn-warning\"  href=\"#\" > deaktivieren </a> ";   ?>

<table class="table table-striped table-hover">
    
    <thead>
        <tr>
            <th>Details</th>
            <th>Id</th>
            <th>Benutzername</th>
            <th>Anzeigename</th>
            <th>Name</th>
            <th>Email</th>
            <th>Status</th>
            <th>(De/)Aktivieren</th>
            <th>Löschen</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach ($this->users as $user) : ?>
        <tr>
            <td><a class="btn btn-default" href="<?= $this->actionUrls['details'] . '/id=' . $user->getUserId() ?>">Details</a></td>
            <td><?= $user->getUserId() ?></td>
            <td><?= $user->getUserName() ?></td>
            <td><?= $user->getDisplayName() ?></td>
            <td><?= $user->getName() ?></td>
            <td><a href="mailto:<?= $user->getEmail() ?>"> <?= $user->getEmail() ?> </a> </td>
            <td><?= $user->getState() ?></td>
            <td><?= $user->getState() ? $deaktivieren : $aktivieren; ?>  </td>
            <td><a class="btn btn-danger" href="#">löschen</a></td>
        </tr>
        <?php endforeach; ?>
        
    </tbody>
    
</table>