<div class="panel panel-default">

            <div class="panel-heading">
                Ihre Benutzereinstellungen:
            </div>

            <div class="panel-body">

                <table class="table table-responsive table-hover">
                    <tbody>

                        <tr>
                            <th>Anzeigename</th>
                            <td><a href="#">ändern</a></td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td><a href="<?php echo $this->actionUrls['changeMail']; ?>">ändern</a></td>
                        </tr>
                        <tr>
                            <th>Passwort</th>
                            <td><a href="<?php echo $this->actionUrls['changePassword']; ?>">ändern</a></td>
                        </tr>
                        <tr>
                            <th>Benutzerkonto</th>
                            <td><a href="#">löschen</a></td>
                        </tr>
                    </tbody>

                </table>


            </div>
        </div>

