<div class="panel panel-default">

            <div class="panel-heading">
                Ihre Benutzereinstellungen:
            </div>

            <div class="panel-body">

                <table class="table table-responsive table-hover">
                    <tbody>

                        <tr>
                            <th>Email</th>
                            <td><a src="#">ändern</a></td>
                        </tr>
                        <tr>
                            <th>Passwort</th>
                            <td><a src="#">ändern</a></td>
                        </tr>
                        <tr>
                            <th>Benutzerkonto</th>
                            <td><a src="#">löschen</a></td>
                        </tr>
                    </tbody>

                </table>


            </div>

        </div>