

<div class="row">

    <div class="col-md-4">

        <?php echo $this->ztbForm($this->form); ?>

    </div>

    <div class="col-md-8">

        <div style="
            overflow: auto;
            width: 1280px;
            height: 720px;
            -ms-zoom: 0.5;
            -moz-transform: scale(0.5);
            -moz-transform-origin: 0px 0;
            -o-transform: scale(0.5);
            -o-transform-origin: 0 0;
            -webkit-transform: scale(0.5);
            -webkit-transform-origin: 0 0; ">

            <?php echo $this->previewWidget; ?>
        </div>
    </div>


</div>