<?php
    $this->layout()->setVariable('tasks', array( 'neu' => array(
                    'icon'   => '/img/fachhochschule/icons/new-16.png',
                    'target' => '/fachhochschule/infoscript/create',
                )
            )
        );
?>


<h2 class="h2"> Infoscripte anzeigen </h2>

<?php echo $this->partial('base/flash.phtml'); ?>



<?php echo $this->partial('base/infoscript/partial/infoscript.phtml'); ?>